//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuisnessLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyberShopeeEntities2 : DbContext
    {
        public CyberShopeeEntities2()
            : base("name=CyberShopeeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<orderDetails> orderDetails { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<shoppingCart> shoppingCart { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
